---
title: "hw5"
output: html_document
---

### 5.1
```{r}
chairs = read.csv('https://raw.githubusercontent.com/agricolamz/2019_data_analysis_for_linguists/master/data/students/evgeniarubanova/hw5_CA_MCA/hw5_chairs.csv')

mca_chairs = chairs[,-c(1, 2, 3)]

MCA <- MASS::mca(mca_chairs)

chairs <- cbind(chairs, MCA$rs)
variables <- as_data_frame(MCA$cs)
variables$var_names <- rownames(MCA$cs)

chairs %>%
  ggplot(aes(`1`, `2`))+
  geom_point(aes(color = Category))+
  stat_ellipse(aes(color = Category))+
  geom_text(data = variables, aes(`1`, `2`, label = var_names), size = 3)+
  theme_bw()+
  scale_x_continuous(limits = c(-0.015, 0.02))
```
### 5.2
```{r}
```

### 5.3
```{r}
colreg <- read.csv('https://raw.githubusercontent.com/agricolamz/2019_data_analysis_for_linguists/master/data/students/evgeniarubanova/hw5_CA_MCA/hw5_colreg.csv')

rownames(colreg) <- colreg$colors
ca <- ca(colreg[-5])

colreg_col <- data.frame(ca$colcoord)
colreg_col$rows <- rownames(ca$colcoord)

colreg_row <- data.frame(ca$rowcoord)
colreg_row$rows <- rownames(ca$rowcoord)

colreg_col %>%
  ggplot(aes(Dim1, Dim2, label = rows))+
  geom_text(color = "green")+
  geom_text(data = colreg_row, color = "purple")+
  theme_bw()
```

### 5.4
```{r}
```